### ISSUE TITLE
Returning 404 on OPTION check for file results in upload being unable to happen

### ISSUE THREAD

**Issue by KieranP** [janko-m/tus-ruby-server#2]
If a file was previously uploaded, before but no longer exists on the server because of the expirator, then they upload the exact same file (so that the fingerprint matches and the localstorage URL is reusued), tus-js will run an OPTIONS calls to the server to fetch headers. However, ruby-tus returns a 404, which results in the upload failing because the preflight check failed. In reality, the options call should return 204 always, and then when it does a HEAD to the url, then it gets the 404, and it realises that it needs to start a new upload. Basically, this server needs to return 204 for checkflight (options), never a 404 or it all fails.

**Comment by KieranP** [comment]
@janko-m Here is the required change to make things work properly:

https://github.com/90seconds/tus-ruby-server/commit/c20ab299d7724570f003d3119f96fe7c0c5c0743

**Comment by janko-m** [comment]
Thanks for letting me know. Yeah, that totally makes sense, I'll make the change shortly.

**Comment by KieranP** [comment]
@janko-m Awesome, thank you :-) Awesome work on this tus server btw. It's working really well in production. I've created a ticket on the tus.io protocol git repo mentioning this ticket, so hopefully the spec gets adjusted to say that a 204 response is required on options requests, so other servers don't run into this issue.
