### ISSUE TITLE
Getting tus-ruby-server to run behind a reverse proxy

### ISSUE THREAD

**Issue by shawnthetechie** [janko-m/tus-ruby-server#9]
I'm trying to run tus-ruby-server behind a reverse proxy via SSL and would like to use your approach instead of tusd's docker solution. Is there a way to add -behind-proxy so that it pays attention to special headers when used in conjunction with a proxy?

**Comment by janko-m** [comment]
Tus-ruby-server currently doesn't have any special support for reverse proxies, but it could be added. We could just copy what tusd does. Would you like to try adding the support for reverse proxies? If not, I can take a stab at it.

**Comment by shawnthetechie** [comment]
I reckon we could do it like tusd binary does with the use of -behind-proxy flag but I'm trying to figure out where to go in this repo.

**Comment by shawnthetechie** [comment]
I tried setting opts[:behind_proxy] = true but that didn't work. I'll try to tinker around but if you can take a stab at it, that would be very much appreciated.

**Comment by janko-m** [comment]
You misunderstood, tus-ruby-server *doesn’t* have the “behind proxy” feature yet, it would need to be added. I was asking if you would like to send a PR that adds this feature, and make `Tus::Server.opts[:behind_proxy] = true` enable that feature.

**Comment by shawnthetechie** [comment]
Thanks for making that clear. Unfortunately, the makers of the picocandy/rubytus aren't really active anymore. I raised an issue a few days back and have yet to receive a response. I wonder if there's a workaround we can do on our part.

**Comment by janko-m** [comment]
tus-ruby-server and rubytus are two separate implementations of the Ruby server for the tus protocol. tus-ruby-server doesn't use rubytus, it's an alternative, and unlike rubytus, this one *is* actively maintained (*I*'m maintaining it 😃). So there is no need to do any workarounds, we can just add this feature to tus-ruby-server.

I was just asking if you would like to add that feature, because you probably understand what should be implemented better than me 😉. If the codebase is too overwhelming for you, I can work on adding it, I just need to first research what is it that needs to be changed.

**Comment by shawnthetechie** [comment]
That makes a lot of sense. Appreciate your quick response and thank you for doing what you do! 😃 

I just sent a PR but would definitely need more inputs since I couldn't get it to work, at least for now.

The official reference implementation of tus has an answer [https://github.com/tus/tusd/blob/master/README.md#can-i-run-tusd-behind-a-reverse-proxy](url) for reverse proxy with SSL and hopefully that helps as far as what is it that needs to be changed.

**Comment by janko-m** [comment]
> I just sent a PR but would definitely need more inputs since I couldn't get it to work, at least for now.

That's because you need to make something actually *happen* when `:behind_proxy` is set to `true` 😉. Ok, I'll see what I can do.

**Comment by janko-m** [comment]
Nice, it seems that Rack (the base of the Roda web framework tus-ruby-server uses) already automatically handles the [proxy headers](https://github.com/rack/rack/blob/42e48013dd1b6dbda990dfa3851856c199b0b1f9/lib/rack/request.rb#L122-L126) in `Rack::Request`. So we should be good to go, there isn't anything that needs to be changed in tus-ruby-server, it already supports reverse proxies.
